// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --local > src/lib/database.types.ts
// For now, we'll use a minimal type definition

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          context: string | null
          native_language: string | null
          target_language: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          context?: string | null
          native_language?: string | null
          target_language?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          context?: string | null
          native_language?: string | null
          target_language?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      words: {
        Row: {
          id: string
          word: string
          base_word: string | null
          language: string | null
          translation_of: string | null
          created_at: string
        }
        Insert: {
          id?: string
          word: string
          base_word?: string | null
          language?: string | null
          translation_of?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          word?: string
          base_word?: string | null
          language?: string | null
          translation_of?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
